from typing import List
from sqlmodel import Session, select
from logging_client import logger
from celery_app import celery_app
import ai
from models import Word
from quick_write.quick_write_repository import QuickWriteRepository


@celery_app.task(name="tasks.quick_write.generate")
def generate_quick_write_exercises_task(user_id: int, word_ids: List[int], amount: int = 10) -> dict:
    """
    Genera ejercicios de Quick Write para una lista de palabras usando IA y los guarda en la BD.

    Args:
        user_id: ID del usuario (para logging)
        word_ids: Lista de IDs de palabras para las que generar ejercicios
        amount: Número de ejercicios a generar (default 10)

    Returns:
        Diccionario con status y cantidad de ejercicios creados
    """
    import sys
    import os
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + '/..')

    from db import engine

    if not word_ids:
        logger.warning(f"[QuickWriteGenerator] No words provided for user {user_id}")
        return {"status": "error", "message": "No words provided", "created": 0}

    logger.info(f"[QuickWriteGenerator] Generating quick write exercises for {len(word_ids)} words (user {user_id})")

    try:
        # Crear nueva sesión para la tarea
        with Session(engine) as db:
            # Cargar palabras por sus IDs
            words = db.exec(
                select(Word).where(Word.id.in_(word_ids), Word.user_id == user_id)
            ).all()

            if not words:
                logger.warning(f"[QuickWriteGenerator] Words not found for user {user_id}")
                return {"status": "error", "message": "Words not found", "created": 0}

            logger.info(f"[QuickWriteGenerator] Found {len(words)} words, generating exercises...")

            # Generar ejercicios usando IA
            exercises = ai.generate_quick_write_exercises(words)

            if not exercises:
                logger.warning(f"[QuickWriteGenerator] No exercises generated by AI for user {user_id}")
                return {"status": "error", "message": "No exercises generated", "created": 0}

            logger.info(f"[QuickWriteGenerator] AI generated {len(exercises)} quick write exercises, saving to DB...")

            # Guardar ejercicios en la base de datos
            repo = QuickWriteRepository(db)
            created_count = 0

            for exercise in exercises:
                try:
                    prompt = exercise.get("prompt", "")
                    emoji = exercise.get("emoji", "✍️")
                    words_list = None

                    # Extraer palabras del ejercicio si existen
                    if "words" in exercise:
                        words_data = exercise.get("words", [])
                        if isinstance(words_data, list) and len(words_data) > 0:
                            # Si es una lista de dicts con "word", extraer solo los textos
                            if isinstance(words_data[0], dict) and "word" in words_data[0]:
                                words_list = [w.get("word", "") for w in words_data if isinstance(w, dict)]
                            # Si es una lista de strings, usarla directamente
                            elif isinstance(words_data[0], str):
                                words_list = words_data

                    if prompt:
                        repo.create(
                            user_id=user_id,
                            prompt=prompt,
                            emoji=emoji,
                            words=words_list,
                            original_content=None,
                            corrected_content=None,
                            has_corrections=False
                        )
                        created_count += 1
                        logger.debug(f"[QuickWriteGenerator] Saved exercise: {prompt[:50]}...")
                    else:
                        logger.warning(f"[QuickWriteGenerator] Exercise missing prompt, skipping")

                except Exception as e:
                    logger.error(f"[QuickWriteGenerator] Error saving exercise: {e}", exc_info=True)
                    continue

            logger.info(f"[QuickWriteGenerator] Successfully created {created_count} quick write exercises for user {user_id}")
            return {
                "status": "success",
                "message": f"Created {created_count} exercises",
                "created": created_count
            }

    except Exception as e:
        logger.error(
            f"[QuickWriteGenerator] Error generating quick write exercises for user {user_id}: {e}",
            exc_info=True
        )
        return {"status": "error", "message": str(e), "created": 0}


class QuickWriteGenerator:
    """Wrapper para llamar a tasks de generación de quick write exercises"""

    @staticmethod
    def generate(user_id: int, word_ids: List[int], amount: int = 10):
        """Solicita generación de quick write exercises"""
        return generate_quick_write_exercises_task.delay(user_id, word_ids, amount)
