"""init

Revision ID: 0e2a8052665e
Revises: 
Create Date: 2026-08-25 17:57:48.240364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e2a8052665e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INITIAL', 'EXPLORE', name='exampletype'), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(), nullable=True),
    sa.Column('normalized', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('enqueued', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_enqueued'), 'examples', ['enqueued'], unique=False)
    op.create_index(op.f('ix_examples_favorited_at'), 'examples', ['favorited_at'], unique=False)
    op.create_index(op.f('ix_examples_is_consumed'), 'examples', ['is_consumed'], unique=False)
    op.create_index(op.f('ix_examples_normalized'), 'examples', ['normalized'], unique=True)
    op.create_index(op.f('ix_examples_sequence'), 'examples', ['sequence'], unique=False)
    op.create_index(op.f('ix_examples_type'), 'examples', ['type'], unique=False)
    op.create_table('explore_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_examples', sa.Integer(), nullable=False),
    sa.Column('ai_mixed_generation_amount', sa.Integer(), nullable=False),
    sa.Column('ai_simple_generation_amount', sa.Integer(), nullable=False),
    sa.Column('recycled_words_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explore_configurations_max_examples'), 'explore_configurations', ['max_examples'], unique=True)
    op.create_table('generation_queue_monitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'GENERATING', name='generationqueuemonitorstatus'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_queue_monitor_status'), 'generation_queue_monitor', ['status'], unique=False)
    op.create_table('global_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_configurations_key'), 'global_configurations', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('content_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXAMPLE', 'BEST_OPTIONS', name='contenttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONSUMED', name='contentqueuestatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_queue_content_id'), 'content_queue', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_queue_priority'), 'content_queue', ['priority'], unique=False)
    op.create_index(op.f('ix_content_queue_status'), 'content_queue', ['status'], unique=False)
    op.create_index(op.f('ix_content_queue_type'), 'content_queue', ['type'], unique=False)
    op.create_index(op.f('ix_content_queue_user_id'), 'content_queue', ['user_id'], unique=False)
    op.create_table('learning_path_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXAMPLE', 'BEST_OPTIONS', name='contenttype'), nullable=False),
    sa.Column('current_segment', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_cursor_type'), 'learning_path_cursor', ['type'], unique=False)
    op.create_index(op.f('ix_learning_path_cursor_user_id'), 'learning_path_cursor', ['user_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('meaning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('synonyms', sa.JSON(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('frequency', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('context', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('source_text', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('normalized', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_boosted', sa.Boolean(), nullable=False),
    sa.Column('boosted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_main'), 'words', ['main'], unique=False)
    op.create_index(op.f('ix_words_normalized'), 'words', ['normalized'], unique=True)
    op.create_table('best_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_option', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('normalized', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('enqueued', sa.Boolean(), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_best_options_enqueued'), 'best_options', ['enqueued'], unique=False)
    op.create_index(op.f('ix_best_options_is_consumed'), 'best_options', ['is_consumed'], unique=False)
    op.create_index(op.f('ix_best_options_normalized'), 'best_options', ['normalized'], unique=True)
    op.create_index(op.f('ix_best_options_sequence'), 'best_options', ['sequence'], unique=False)
    op.create_index(op.f('ix_best_options_word_id'), 'best_options', ['word_id'], unique=False)
    op.create_table('example_words',
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('text_form', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['examples.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('example_id', 'word_id')
    )
    op.create_table('learning_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXAMPLE', 'BEST_OPTIONS', name='contenttype'), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_segment'), 'learning_path', ['segment'], unique=False)
    op.create_index(op.f('ix_learning_path_type'), 'learning_path', ['type'], unique=False)
    op.create_index(op.f('ix_learning_path_user_id'), 'learning_path', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_path_word_id'), 'learning_path', ['word_id'], unique=False)
    op.create_table('learning_path_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXAMPLE', 'BEST_OPTIONS', name='contenttype'), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_history_segment'), 'learning_path_history', ['segment'], unique=False)
    op.create_index(op.f('ix_learning_path_history_type'), 'learning_path_history', ['type'], unique=False)
    op.create_index(op.f('ix_learning_path_history_user_id'), 'learning_path_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_learning_path_history_word_id'), 'learning_path_history', ['word_id'], unique=False)
    op.create_table('word_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXAMPLE', 'BEST_OPTIONS', name='contenttype'), nullable=False),
    sa.Column('learning_state', sa.Enum('NEW', 'LEARNING', 'REINFORCING', 'SPACING', 'ALMOST_LEARNED', 'LEARNED', 'REVIEW', name='learningstate'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('current_cycle_seen', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_statistics_learning_state'), 'word_statistics', ['learning_state'], unique=False)
    op.create_index(op.f('ix_word_statistics_type'), 'word_statistics', ['type'], unique=False)
    op.create_index(op.f('ix_word_statistics_word_id'), 'word_statistics', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_statistics_word_id'), table_name='word_statistics')
    op.drop_index(op.f('ix_word_statistics_type'), table_name='word_statistics')
    op.drop_index(op.f('ix_word_statistics_learning_state'), table_name='word_statistics')
    op.drop_table('word_statistics')
    op.drop_index(op.f('ix_learning_path_history_word_id'), table_name='learning_path_history')
    op.drop_index(op.f('ix_learning_path_history_user_id'), table_name='learning_path_history')
    op.drop_index(op.f('ix_learning_path_history_type'), table_name='learning_path_history')
    op.drop_index(op.f('ix_learning_path_history_segment'), table_name='learning_path_history')
    op.drop_table('learning_path_history')
    op.drop_index(op.f('ix_learning_path_word_id'), table_name='learning_path')
    op.drop_index(op.f('ix_learning_path_user_id'), table_name='learning_path')
    op.drop_index(op.f('ix_learning_path_type'), table_name='learning_path')
    op.drop_index(op.f('ix_learning_path_segment'), table_name='learning_path')
    op.drop_table('learning_path')
    op.drop_table('example_words')
    op.drop_index(op.f('ix_best_options_word_id'), table_name='best_options')
    op.drop_index(op.f('ix_best_options_sequence'), table_name='best_options')
    op.drop_index(op.f('ix_best_options_normalized'), table_name='best_options')
    op.drop_index(op.f('ix_best_options_is_consumed'), table_name='best_options')
    op.drop_index(op.f('ix_best_options_enqueued'), table_name='best_options')
    op.drop_table('best_options')
    op.drop_index(op.f('ix_words_normalized'), table_name='words')
    op.drop_index(op.f('ix_words_main'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_learning_path_cursor_user_id'), table_name='learning_path_cursor')
    op.drop_index(op.f('ix_learning_path_cursor_type'), table_name='learning_path_cursor')
    op.drop_table('learning_path_cursor')
    op.drop_index(op.f('ix_content_queue_user_id'), table_name='content_queue')
    op.drop_index(op.f('ix_content_queue_type'), table_name='content_queue')
    op.drop_index(op.f('ix_content_queue_status'), table_name='content_queue')
    op.drop_index(op.f('ix_content_queue_priority'), table_name='content_queue')
    op.drop_index(op.f('ix_content_queue_content_id'), table_name='content_queue')
    op.drop_table('content_queue')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_global_configurations_key'), table_name='global_configurations')
    op.drop_table('global_configurations')
    op.drop_index(op.f('ix_generation_queue_monitor_status'), table_name='generation_queue_monitor')
    op.drop_table('generation_queue_monitor')
    op.drop_index(op.f('ix_explore_configurations_max_examples'), table_name='explore_configurations')
    op.drop_table('explore_configurations')
    op.drop_index(op.f('ix_examples_type'), table_name='examples')
    op.drop_index(op.f('ix_examples_sequence'), table_name='examples')
    op.drop_index(op.f('ix_examples_normalized'), table_name='examples')
    op.drop_index(op.f('ix_examples_is_consumed'), table_name='examples')
    op.drop_index(op.f('ix_examples_favorited_at'), table_name='examples')
    op.drop_index(op.f('ix_examples_enqueued'), table_name='examples')
    op.drop_table('examples')
    # ### end Alembic commands ###
