"""exm

Revision ID: 26c980361c87
Revises: 
Create Date: 2026-06-28 21:52:21.465086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '26c980361c87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examples', sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('examples', sa.Column('times_seen', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examples', 'times_seen')
    op.drop_column('examples', 'type')
    # ### end Alembic commands ###
