"""add_isconsumed

Revision ID: 56c82212e604
Revises: a73ed0fa3150
Create Date: 2026-08-25 09:35:50.816774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56c82212e604'
down_revision: Union[str, Sequence[str], None] = 'a73ed0fa3150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'best_options',
        sa.Column('is_consumed', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.create_index(op.f('ix_best_options_is_consumed'), 'best_options', ['is_consumed'], unique=False)

    op.add_column(
        'examples',
        sa.Column('is_consumed', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.create_index(op.f('ix_examples_is_consumed'), 'examples', ['is_consumed'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examples_is_consumed'), table_name='examples')
    op.drop_column('examples', 'is_consumed')
    op.drop_index(op.f('ix_best_options_is_consumed'), table_name='best_options')
    op.drop_column('best_options', 'is_consumed')
    # ### end Alembic commands ###
