"""add_fav_to_example

Revision ID: 6f4c1cef49f8
Revises: ec9399a7bad5
Create Date: 2026-08-24 07:02:45.639539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f4c1cef49f8'
down_revision: Union[str, Sequence[str], None] = 'ec9399a7bad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'examples',
        sa.Column(
            'is_favorite',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false")
        )
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examples', 'is_favorite')
    # ### end Alembic commands ###
