"""add_fav_date

Revision ID: a73ed0fa3150
Revises: 6f4c1cef49f8
Create Date: 2026-08-25 09:18:34.232085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a73ed0fa3150'
down_revision: Union[str, Sequence[str], None] = '6f4c1cef49f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examples', sa.Column('favorited_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_examples_favorited_at'), 'examples', ['favorited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examples_favorited_at'), table_name='examples')
    op.drop_column('examples', 'favorited_at')
    # ### end Alembic commands ###
