"""quick_write

Revision ID: b88de71a086a
Revises: 0e2a8052665e
Create Date: 2026-08-28 16:16:11.013938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b88de71a086a'
down_revision: Union[str, Sequence[str], None] = '0e2a8052665e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_write',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('emoji', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('words', sa.JSON(), nullable=True),
    sa.Column('original_content', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('corrected_content', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('has_corrections', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_write_created_at'), 'quick_write', ['created_at'], unique=False)
    op.create_index(op.f('ix_quick_write_is_active'), 'quick_write', ['is_active'], unique=False)
    op.create_index(op.f('ix_quick_write_user_id'), 'quick_write', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quick_write_user_id'), table_name='quick_write')
    op.drop_index(op.f('ix_quick_write_is_active'), table_name='quick_write')
    op.drop_index(op.f('ix_quick_write_created_at'), table_name='quick_write')
    op.drop_table('quick_write')
    # ### end Alembic commands ###
