"""user_configuration

Revision ID: bac6e1e744f8
Revises: c1234567890b7
Create Date: 2026-09-15 14:16:49.971091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bac6e1e744f8'
down_revision: Union[str, Sequence[str], None] = 'c1234567890b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('max_words', sa.Integer(), nullable=True),
    sa.Column('max_examples', sa.Integer(), nullable=True),
    sa.Column('max_best_options', sa.Integer(), nullable=True),
    sa.Column('max_collocations', sa.Integer(), nullable=True),
    sa.Column('max_quick_writes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_configurations_user_id'), 'user_configurations', ['user_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('total_examples', sa.Integer(), nullable=False),
    sa.Column('total_best_options', sa.Integer(), nullable=False),
    sa.Column('total_collocations', sa.Integer(), nullable=False),
    sa.Column('total_quick_writes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_configurations_user_id'), table_name='user_configurations')
    op.drop_table('user_configurations')
