"""collocations

Revision ID: c1234567890ab
Revises: b88de71a086a
Create Date: 2026-09-01 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1234567890ab'
down_revision: Union[str, Sequence[str], None] = 'b88de71a086a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('phrase', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collocations_created_at'), 'collocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_collocations_is_active'), 'collocations', ['is_active'], unique=False)
    op.create_index(op.f('ix_collocations_user_id'), 'collocations', ['user_id'], unique=False)
    op.create_index(op.f('ix_collocations_word_id'), 'collocations', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collocations_word_id'), table_name='collocations')
    op.drop_index(op.f('ix_collocations_user_id'), table_name='collocations')
    op.drop_index(op.f('ix_collocations_is_active'), table_name='collocations')
    op.drop_index(op.f('ix_collocations_created_at'), table_name='collocations')
    op.drop_table('collocations')
    # ### end Alembic commands ###
