[
  {
    "main": "zombie",
    "meaning": "a dead person brought back to life mysteriously",
    "synonyms": ["undead", "corpse", "monster"],
    "type": "noun",
    "frequency": "common",
    "level": 1,
    "context": "horror",
    "source_text": "A zombie slowly emerged from the dark hallway.",
    "examples": [
        "The zombie walked through the empty street.",
        "He wore a scary zombie costume today.",
        "The movie features a terrifying zombie outbreak.",
        "I felt like a zombie this morning.",
        "A hidden zombie waited behind the door.",
        "Fight off the hungry zombie right now.",
        "She loves reading classic zombie horror books.",
        "The actor turned into a creepy zombie.",
        "They locked the doors to stop the zombie.",
        "The groaning zombie scared the entire group.",
    ]
  },
  {
    "main": "tiger",
    "meaning": "a large wild cat with stripes",
    "synonyms": ["feline", "predator", "cat"],
    "type": "noun",
    "frequency": "common",
    "level": 1,
    "context": "animals",
    "source_text": "The tiger watched its prey from the grass.",
    "examples": [
        "The wild tiger hunted in the grass.",
        "We saw a giant tiger yesterday afternoon.",
        "A tiger has sharp claws and teeth.",
        "Bright stripes cover the strong tiger body.",
        "The mother tiger protects her young cubs.",
        "A loud tiger roar echoed through forest.",
        "Conservationists work to save the wild tiger.",
        "The tiger moved silently across the river.",
        "That sleepy tiger rests under the tree.",
        "Feed the hungry tiger some fresh meat.",
    ]
  },
  {
    "main": "wander",
    "meaning": "to walk around without a particular destination",
    "synonyms": ["roam", "drift", "stroll"],
    "type": "verb",
    "frequency": "common",
    "level": 2,
    "context": "movement",
    "source_text": "He wandered through the forest for hours.",
    "examples": [
        "We like to wander through old streets.",
        "Do not wander off without your shoes.",
        "Tourists wander around the famous museum today.",
        "They wander in the woods for hours.",
        "My thoughts wander during long boring lectures.",
        "We will wander along the quiet beach.",
        "Children love to wander in big parks.",
        "Never wander away from your group here.",
        "The cows wander across the open field.",
        "I often wander through local book shops.",
    ]
  },
  {
    "main": "stumble",
    "meaning": "to almost fall while walking or moving",
    "synonyms": ["trip", "stagger", "falter"],
    "type": "verb",
    "frequency": "common",
    "level": 2,
    "context": "movement",
    "source_text": "He stumbled over a stone in the road.",
    "examples": [
        "Do not stumble on the wet steps.",
        "He might stumble over his long shoes.",
        "I saw her stumble on the rock.",
        "The tired runner began to stumble slowly.",
        "You could stumble in this dark room.",
        "Speak clearly so you do not stumble.",
        "I might stumble upon a good book.",
        "Watch out or you will stumble now.",
        "The sleepy kid started to stumble forward.",
        "Do not let small obstacles make you stumble.",
    ]
  },
  {
    "main": "carve out",
    "meaning": "to create something through effort or persistence",
    "synonyms": ["create", "establish", "build", "forge"],
    "type": "phrasal_verb",
    "frequency": "common",
    "level": 3,
    "context": "achievement",
    "source_text": "She carved out a successful career for herself.",
    "examples": [
        "She will carve out a great career.",
        "Please carve out time for our meeting.",
        "Rivers carve out deep valleys over time.",
        "He tried to carve out his path.",
        "We can carve out a small garden.",
        "They want to carve out new markets.",
        "You must carve out an hour daily.",
        "She managed to carve out her spot.",
        "Artists carve out shapes from solid stone.",
        "We need to carve out more space.",
    ]
  },
  {
    "main": "spring out",
    "meaning": "to suddenly move or appear from somewhere",
    "synonyms": ["emerge", "burst", "jump", "leap"],
    "type": "phrasal_verb",
    "frequency": "uncommon",
    "level": 2,
    "context": "movement",
    "source_text": "A rabbit sprang out from behind the bush.",
    "examples": [
        "A wild cat will spring out suddenly.",
        "Bright flowers spring out every single spring.",
        "Secrets can spring out when you talk.",
        "The hidden trap might spring out now.",
        "Fresh water will spring out from rocks.",
        "Rabbits spring out from the tall grass.",
        "New ideas spring out during our meetings.",
        "Toys spring out of the surprise box.",
        "He saw a frog spring out quickly.",
        "We watched the dog spring out outside.",
    ]
  },
  {
    "main": "loom",
    "meaning": "to appear large and threatening nearby suddenly",
    "synonyms": ["tower", "emerge", "threaten", "overhang"],
    "type": "verb",
    "frequency": "uncommon",
    "level": 3,
    "context": "appearance",
    "source_text": "Dark clouds loomed over the distant hills.",
    "examples": [
        "Dark clouds loom over the blue sky.",
        "Tall mountains loom in the cold distance.",
        "Hard exams loom ahead for all students.",
        "Giant shadows loom against the old wall.",
        "Big troubles loom if we act late.",
        "Monster figures loom through the thick fog.",
        "High cliffs loom above the stormy ocean.",
        "New dangers loom near the dark forest.",
        "Tough choices loom before the young team.",
        "Strange shapes loom inside the quiet room.",
    ]
  },  
  {
    "main": "ominous",
    "meaning": "suggesting that something bad may happen soon",
    "synonyms": ["threatening", "menacing", "foreboding", "sinister"],
    "type": "adjective",
    "frequency": "uncommon",
    "level": 3,
    "context": "atmosphere",
    "source_text": "An ominous silence filled the room.",
    "examples": [
        "The sky turned an ominous dark color.",
        "We heard an ominous noise last night.",
        "An ominous sign appeared on the road.",
        "His cold voice sounded very ominous today.",
        "The dark clouds look ominous right now.",
        "She felt an ominous presence behind her.",
        "That silence in the house was ominous.",
        "An ominous warning came from the chief.",
        "The ruined castle had an ominous vibe.",
        "Heavy rain brought an ominous dark storm.",
    ]
  },
  {
    "main": "peril",
    "meaning": "serious danger or risk of harm",
    "synonyms": ["danger", "hazard", "risk", "jeopardy"],
    "type": "noun",
    "frequency": "rare",
    "level": 3,
    "context": "danger",
    "source_text": "They knew they were walking into great peril.",
    "examples": [
        "They faced great peril in the jungle.",
        "The brave hero escaped from extreme peril.",
        "Driving fast puts your life in peril.",
        "Wild animals face serious peril every day.",
        "The old bridge is a great peril.",
        "We must save the ship from peril.",
        "The lost Hiker was in deep peril.",
        "Ignoring the rules leads to real peril.",
        "High winds create peril for small boats.",
        "They walked into peril without knowing it.",
    ]
  },
  {
    "main": "eerie",
    "meaning": "strange and frightening in a mysterious way",
    "synonyms": ["creepy", "spooky", "unheimlich", "uncanny"],
    "type": "adjective",
    "frequency": "uncommon",
    "level": 2,
    "context": "atmosphere",
    "source_text": "An eerie glow lit up the abandoned cabin.",
    "examples": [
        "An eerie light shined through the window.",
        "The empty street felt completely eerie tonight.",
        "We heard an eerie sound outdoors late.",
        "A quiet lake can look very eerie.",
        "She sang an eerie song about ghosts.",
        "That old house gives an eerie feeling.",
        "An eerie silence filled the entire cave.",
        "The foggy forest looked eerie at night.",
        "He gave an eerie smile to everyone.",
        "Green glowing eyes look very eerie here.",
    ]
  },
  {
    "main": "ghost",
    "meaning": "the spirit of a dead person that appears to the living",
    "synonyms": ["phantom", "spirit", "specter", "wraith"],
    "type": "noun",
    "frequency": "common",
    "level": 1,
    "context": "horror",
    "source_text": "The old house was believed to be haunted by a ghost.",
    "examples": [
        "A scary ghost lived in that castle.",
        "I saw a pale ghost last night.",
        "She told a famous ghost story tonight.",
        "The friendly ghost helped the young kids.",
        "Nobody believes in a real ghost nowadays.",
        "The phantom looked like a white ghost.",
        "A small ghost appeared in the mirror.",
        "He was as quiet as a ghost.",
        "That camera caught a mysterious ghost image.",
        "The old legend features a crying ghost.",
    ]
  },
  {
    "main": "ambush",
    "meaning": "a surprise attack from a hidden position",
    "synonyms": ["trap", "surprise attack", "waylay"],
    "type": "noun",
    "frequency": "uncommon",
    "level": 3,
    "context": "combat",
    "source_text": "The soldiers walked straight into an ambush.",
    "examples": [
        "The soldiers planned a sudden ambush today.",
        "Enemies set a dangerous ambush in darkness.",
        "The tiger waited to ambush its prey.",
        "They walked straight into a hidden ambush.",
        "Our squad survived the terrible enemy ambush.",
        "The police foiled a planned street ambush.",
        "Shadows hid the squad for an ambush.",
        "A surprise ambush caught them off guard.",
        "Wolves set an ambush near the river.",
        "Never march blindly into a fatal ambush.",
    ]
  },
  {
    "main": "relentless",
    "meaning": "continuing without stopping or showing mercy",
    "synonyms": ["unforgiving", "persistent", "unyielding", "ruthless"],
    "type": "adjective",
    "frequency": "common",
    "level": 3,
    "context": "behavior",
    "source_text": "The detective was relentless in his search for the truth.",
    "examples": [
        "The relentless rain flooded the entire town.",
        "She is relentless in reaching her goals.",
        "The army faced a relentless enemy attack.",
        "He works with relentless focus every day.",
        "The summer heat was totally relentless today.",
        "Relentless waves crashed against the high cliffs.",
        "Their relentless effort finally brought great success.",
        "A relentless wind blew all night long.",
        "The detective maintained a relentless search here.",
        "She showed relentless courage during hard times.",
    ]
  }
]