import random
from typing import List
from sqlmodel import Session, select
from logging_client import logger
from celery_app import celery_app
import ai


def _shuffle_options_with_correct_index(options: list, correct_option_idx: int) -> tuple:
    """
    Desordena una lista de opciones y retorna la lista desordenada
    junto con el nuevo índice de la opción correcta.

    Args:
        options: Lista de opciones
        correct_option_idx: Índice original de la opción correcta

    Returns:
        tuple: (opciones_desordenadas, nuevo_índice_correcto)
    """
    if not options or correct_option_idx >= len(options):
        return options, correct_option_idx

    shuffled_indices = random.sample(range(len(options)), len(options))
    shuffled_options = [options[i] for i in shuffled_indices]
    new_correct_idx = shuffled_indices.index(correct_option_idx)

    return shuffled_options, new_correct_idx


@celery_app.task(name="tasks.best_options.generate")
def generate_best_options_task(user_id: int, word_ids: List[int]) -> None:
    """
    Genera ejercicios best_option para una lista de palabras usando IA.

    Args:
        user_id: ID del usuario (para logging)
        word_ids: Lista de IDs de palabras para las que generar ejercicios
    """
    import sys
    import os
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + '/..')

    from db import engine
    from models import Word, BestOption

    if not word_ids:
        logger.warning(f"[BestOptionsGenerator] No words provided for user {user_id}")
        return

    logger.info(f"[BestOptionsGenerator] Generating best option exercises for {len(word_ids)} words (user {user_id})")

    try:
        # Crear nueva sesión para la tarea
        with Session(engine) as db:
            # Cargar palabras por sus IDs
            words = db.exec(
                select(Word).where(Word.id.in_(word_ids), Word.user_id == user_id)
            ).all()

            if not words:
                logger.warning(f"[BestOptionsGenerator] Words not found for user {user_id}")
                return

            # Generar ejercicios usando IA
            raw_best_options = ai.generate_best_options_from_words(words)

            if not raw_best_options:
                logger.warning(f"[BestOptionsGenerator] No exercises generated by AI for user {user_id}")
                return

            logger.info(f"[BestOptionsGenerator] AI generated {len(raw_best_options)} exercise sets")

            # Procesar cada set de ejercicios
            for exercise_set in raw_best_options:
                word_id = exercise_set.get("word_id")
                questions = exercise_set.get("questions", [])

                if not questions or not word_id:
                    logger.warning(f"[BestOptionsGenerator] Skipping exercise set for word {word_id} (no questions)")
                    continue

                # Crear un BestOption para cada pregunta
                for sequence_idx, question_data in enumerate(questions, start=1):
                    question_text = question_data.get("question")
                    options = question_data.get("options", [])
                    correct_option_idx = question_data.get("correct_option", 0)

                    if not question_text or not options:
                        logger.warning(f"[BestOptionsGenerator] Skipping question {sequence_idx} for word {word_id}")
                        continue

                    # Desordena las opciones
                    shuffled_options, new_correct_idx = _shuffle_options_with_correct_index(
                        options, correct_option_idx
                    )

                    # Crear la cadena de opciones separadas por ";"
                    options_string = ";".join(shuffled_options)

                    # Crear el BestOption en DB
                    best_option = BestOption(
                        word_id=word_id,
                        question=question_text,
                        options=options_string,
                        correct_option=new_correct_idx
                    )
                    db.add(best_option)
                    db.flush()

            db.commit()
            logger.info(
                f"[BestOptionsGenerator] Successfully created best options for user {user_id}"
            )

    except Exception as e:
        logger.error(
            f"[BestOptionsGenerator] Error generating best options for user {user_id}: {e}",
            exc_info=True
        )


class BestOptionGenerator:
    """Wrapper para llamar a tasks de generación de best options desde ContentPlanner"""

    @staticmethod
    def generate(user_id: int, word_ids: List[int]):
        """Solicita generación de best options"""
        return generate_best_options_task.delay(user_id, word_ids)
